version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre:
      - sphinx-build -vv -b html -d _build/doctrees docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
